# Generated by Django 2.2.24 on 2021-10-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qoura_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='url_title',
            field=models.CharField(blank=True, max_length=130, unique=True),
        ),
    ]
