# Generated by Django 2.2.24 on 2021-10-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qoura_api', '0002_auto_20211022_1101'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
