# Generated by Django 2.2.24 on 2021-10-22 05:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qoura_api', '0003_auto_20211022_1103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('author', 'question')},
        ),
    ]
